baseurl = "https://zhaohuabing.com"
title = "Huabing Blog"
theme = "clean white"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5
hasCJKLanguage = true
themesDir = "themes"
baseURL = ""
publishDir = "public"

[outputs]
home = [ "HTML", "RSS", "Algolia" ]

[params]
header_image = "img/home-bg-jeep.jpg"
SEOTitle = "赵化冰的博客 | Zhaohuabing Blog"
description = "赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。"
keyword = "赵化冰, zhaohuabing, Zhaohuabing, , 赵化冰的网络日志, 赵化冰的博客, Zhaohuabing Blog, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice"
slogan = "路在脚下，心向远方"
image_404 = "img/404-bg.jpg"
title_404 = "你来到了没有知识的荒原 :("
omit_categories = false
page_view_conter = false
leancloud_app_id = ""
leancloud_app_key = ""
algolia_search = true
algolia_appId = ""
algolia_indexName = ""
algolia_apiKey = ""
sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
sidebar_avatar = "img/zhaohuabing.png"
featured_tags = true
featured_condition_size = 1
ba_track_id = ""
disqus_proxy = ""
disqus_site = ""
reward = true
friends = true
bookmarks = false
about_me = true

  [params.social]
  rss = true
  email = "youremail@gmail.com"
  linkedin = "https://www.linkedin.com/in/yourlinkedinid"
  stackoverflow = "https://stackoverflow.com/users/yourstackoverflowid"
  github = "https://github.com/yourgithub"
  wechat = "your wechat qr code image"

  [[params.friend_link]]
  title = "Linda的博客"
  href = "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title = "Martin Fowler"
  href = "https://martinfowler.com"

  [[params.bookmark_link]]
  title = "ServiceMesher"
  href = "http://www.servicemesher.com"

  [[params.bookmark_link]]
  title = "Pxhere"
  href = "https://pxhere.com"

  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"

  [[params.addtional_menus]]
  title = "BOOKS"
  href = "/top/books/"

  [[params.addtional_menus]]
  title = "ARCHIVE"
  href = "/top/archive/"

  [[params.addtional_menus]]
  title = "ABOUT"
  href = "/top/about/"

  [params.algolia]
  vars = [
  "title",
  "summary",
  "date",
  "publishdate",
  "expirydate",
  "permalink"
]
  params = [ "categories", "tags" ]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[markup.tableOfContents]
endLevel = 2
startLevel = 1

[markup.highlight]
style = "dracula"
